Dc el delete items
the-collab-lab/tcl-78-smart-shopping-list pull request #28
Opened 2024-09-16 20:10 UTC by eva-lng

|   | Type |
| --- | ---|
| ✓ | New Feature |
| ✓ | Delete an item from the list |

## Description

A delete button is rendered next to each item in a list. When clicked, the item is deleted from the database.

## Related Issue

closes #12

## Acceptance Criteria

- [x] The `ListItem` component renders a button that allows the user to delete an item from their list when clicked
- [x] Clicking the delete button prompts the user to confirm that they *really* want to delete the item
- [x]  The `deleteItem` function in `api/firebase.js` has been filled out, and deletes the item from the Firestore database

## Type of Changes

`new feature`

## Updates

**Updated UI with rendered delete buttons and pop up window**
![Screenshot 2024-09-16 at 22 06 04](https://github.com/user-attachments/assets/1bb40546-0ab9-4612-9a0a-16008c298225)

## Testing Steps / QA Criteria

1. npm start
2. navigate to List view
3. click on the delete button next to one of the items
4. confirm the pop up message

2024-09-17 13:27 UTC, tataw-cl approved these changes
Excellent work done guys. It works as expected 👌🏾. And whooooo, y'all's speed was something else 😅🔥

2024-09-18 17:15 UTC, Amaka202 requested changes
Well done team!, your feature works mostly.💥
but when I have an internet issue and my delete request could not be completed, I don't see an error message saying why. That will def reduce the users' experience on our app.

I left a suggestion on how you can go about it😊. Let me know if you have any questions!

cc: @didemydn @eva-lng

2024-09-18 17:15 UTC, Amaka202 commented on src/api/firebase.js
> +	}
you can throw the error here and catch it in the component where you are calling deleteItem for appropriate handling

2024-09-18 17:15 UTC, Amaka202 commented on src/views/List.jsx
> +		}
you already have a system of error management from your past issues, you can use it here to show the user an error message. it is always good for a developer to show a good error message to a user as to why an action could not be completed.

2024-09-18 19:39 UTC, GrannyYetta commented
Well done! The item deletion works well for me :) Congrats on the speediest issue yet!

2024-09-19 17:03 UTC, Amaka202 approved these changes

2024-09-19 17:03 UTC, Amaka202 commented on src/views/List.jsx
> +			setErrorMsg('Failed to delete the item. Please try again!');
great! welcone team!!😊💥

2024-09-20 20:45 UTC, merged